[en]
title = "Matsukura Mario"
weight = 1
label = "EN"
contentDir = "content/english"

[it]
title = "Matsukura Mario"
weight = 1
label = "IT"
contentDir = "content/italian"

[jp]
title = "Matsukura Mario"
weight = 1
label = "JP"
contentDir = "content/japanese"